version: '3.8'

services:
  # Research Extractor Service
  research-extractor:
    build:
      context: .
      dockerfile: docker/research-extractor/Dockerfile
    container_name: research-extractor
    restart: "no"  # One-time run for scraping
    volumes:
      - ./logs:/app/logs
      - ./scripts/Gemini/research_extractor:/app
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - research

  # LLM Service
  llm-service:
    build:
      context: .
      dockerfile: docker/llm-service/Dockerfile
    container_name: llm-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./utils:/app/utils
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY=${API_KEY:-}
    profiles:
      - llm

  # Courses Extractor Service
  courses-extractor:
    build:
      context: .
      dockerfile: docker/courses-extractor/Dockerfile
    container_name: courses-extractor
    restart: "no"  # One-time run for scraping
    volumes:
      - ./logs:/app/logs
      - ./scripts/Gemini/courses_extractor:/app
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - courses

# To run all services together, use:
# docker-compose --profile research --profile llm --profile courses up